[package]
name = "multi-readers"
version = "0.7.0"
edition = "2021"
license = "MIT"
description = "Expose multiple readers as one continuous reader"
keywords = ["readers", "multiple", "async", "seek"]
repository = "https://github.com/cradiy/multi-readers.git"

[dependencies]
tokio = { version = "1.5", optional = true }

[features]
default = []
tokio = ["dep:tokio"]
